import { beforeEach, describe, expect, it, vi } from "vitest";
import { createQueryBuilder, createSupabaseMock } from "@/tests/utils/supabase-mock";

const mocks = vi.hoisted(() => ({
  createClient: vi.fn(),
  getSelectedAccountId: vi.fn(),
  getOrCreateIncomeCategory: vi.fn(),
  getOrCreateDebtCategory: vi.fn(),
  revalidatePath: vi.fn(),
}));

vi.mock("@/lib/supabase/server", () => ({
  createClient: mocks.createClient,
}));

vi.mock("@/actions/accounts", () => ({
  getSelectedAccountId: mocks.getSelectedAccountId,
}));

vi.mock("@/actions/categories", () => ({
  getOrCreateIncomeCategory: mocks.getOrCreateIncomeCategory,
  getOrCreateDebtCategory: mocks.getOrCreateDebtCategory,
}));

vi.mock("next/cache", () => ({
  revalidatePath: mocks.revalidatePath,
}));

import {
  createExpense,
  deleteExpense,
  getExpenses,
  updateExpense,
} from "@/actions/expenses";
import {
  createRecurringExpense,
  deleteRecurringExpense,
  updateRecurringExpense,
} from "@/actions/recurring";

const ACCOUNT_ID = "11111111-1111-4111-8111-111111111111";
const CATEGORY_ID = "22222222-2222-4222-8222-222222222222";

function buildExpenseFormData(overrides?: Record<string, string>) {
  const formData = new FormData();
  formData.set("amount", "32.5");
  formData.set("concept", "Cena");
  formData.set("category_id", CATEGORY_ID);
  formData.set("expense_date", "2026-03-19");
  formData.set("notes", "con amigos");
  formData.set("payment_method", "bank");
  formData.set("is_income", "false");
  formData.set("is_debt", "false");

  for (const [key, value] of Object.entries(overrides ?? {})) {
    formData.set(key, value);
  }

  return formData;
}

function buildRecurringFormData(overrides?: Record<string, string>) {
  const formData = new FormData();
  formData.set("amount", "1200");
  formData.set("concept", "Nómina");
  formData.set("category_id", CATEGORY_ID);
  formData.set("day_of_month", "1");
  formData.set("schedule_type", "monthly");
  formData.set("is_income", "true");

  for (const [key, value] of Object.entries(overrides ?? {})) {
    formData.set(key, value);
  }

  return formData;
}

beforeEach(() => {
  vi.clearAllMocks();
  mocks.getSelectedAccountId.mockResolvedValue(ACCOUNT_ID);
  mocks.getOrCreateIncomeCategory.mockResolvedValue("33333333-3333-4333-8333-333333333333");
  mocks.getOrCreateDebtCategory.mockResolvedValue("44444444-4444-4444-8444-444444444444");
});

describe("expenses CRUD actions", () => {
  it("reads monthly expenses", async () => {
    const expensesQuery = createQueryBuilder({
      data: [{ id: "e1", amount: -20 }],
      error: null,
    });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        tables: {
          expenses: expensesQuery,
        },
      }),
    );

    const result = await getExpenses({ month: 3, year: 2026 });

    expect(expensesQuery.gte).toHaveBeenCalledWith("expense_date", "2026-03-01");
    expect(expensesQuery.lt).toHaveBeenCalledWith("expense_date", "2026-04-01");
    expect(result).toEqual([{ id: "e1", amount: -20 }]);
  });

  it("creates expense with negative sign and account id", async () => {
    const expensesQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          expenses: expensesQuery,
        },
      }),
    );

    const result = await createExpense(buildExpenseFormData());

    expect(result).toEqual({ success: true });
    expect(expensesQuery.insert).toHaveBeenCalledWith(
      expect.objectContaining({
        amount: -32.5,
        category_id: CATEGORY_ID,
        user_id: "user-1",
        account_id: ACCOUNT_ID,
        payment_method: "bank",
      }),
    );
  });

  it("creates income expense with autogenerated category", async () => {
    const expensesQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          expenses: expensesQuery,
        },
      }),
    );

    const formData = buildExpenseFormData({
      is_income: "true",
      category_id: "",
    });

    const result = await createExpense(formData);

    expect(result).toEqual({ success: true });
    expect(mocks.getOrCreateIncomeCategory).toHaveBeenCalled();
    expect(expensesQuery.insert).toHaveBeenCalledWith(
      expect.objectContaining({
        amount: 32.5,
        category_id: "33333333-3333-4333-8333-333333333333",
      }),
    );
  });

  it("updates expense", async () => {
    const expensesQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          expenses: expensesQuery,
        },
      }),
    );

    const result = await updateExpense("exp-1", buildExpenseFormData());

    expect(result).toEqual({ success: true });
    expect(expensesQuery.update).toHaveBeenCalledWith(
      expect.objectContaining({
        amount: -32.5,
        category_id: CATEGORY_ID,
      }),
    );
    expect(expensesQuery.eq).toHaveBeenCalledWith("id", "exp-1");
    expect(expensesQuery.eq).toHaveBeenCalledWith("user_id", "user-1");
  });

  it("deletes expense", async () => {
    const expensesQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          expenses: expensesQuery,
        },
      }),
    );

    const result = await deleteExpense("exp-2");

    expect(result).toEqual({ success: true });
    expect(expensesQuery.delete).toHaveBeenCalled();
    expect(expensesQuery.eq).toHaveBeenCalledWith("id", "exp-2");
    expect(expensesQuery.eq).toHaveBeenCalledWith("user_id", "user-1");
  });
});

describe("recurring CRUD actions", () => {
  it("creates recurring expense", async () => {
    const recurringQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          recurring_expenses: recurringQuery,
        },
      }),
    );

    const result = await createRecurringExpense(buildRecurringFormData());

    expect(result).toEqual({ success: true });
    expect(recurringQuery.insert).toHaveBeenCalledWith(
      expect.objectContaining({
        amount: 1200,
        category_id: CATEGORY_ID,
        account_id: ACCOUNT_ID,
        user_id: "user-1",
      }),
    );
  });

  it("updates recurring expense", async () => {
    const recurringQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          recurring_expenses: recurringQuery,
        },
      }),
    );

    const result = await updateRecurringExpense("rec-1", buildRecurringFormData());

    expect(result).toEqual({ success: true });
    expect(recurringQuery.update).toHaveBeenCalledWith(
      expect.objectContaining({
        amount: 1200,
        category_id: CATEGORY_ID,
      }),
    );
    expect(recurringQuery.eq).toHaveBeenCalledWith("id", "rec-1");
    expect(recurringQuery.eq).toHaveBeenCalledWith("user_id", "user-1");
  });

  it("deletes recurring expense with soft delete", async () => {
    const recurringQuery = createQueryBuilder({ data: null, error: null });

    mocks.createClient.mockResolvedValue(
      createSupabaseMock({
        user: { id: "user-1" },
        tables: {
          recurring_expenses: recurringQuery,
        },
      }),
    );

    const result = await deleteRecurringExpense("rec-2");

    expect(result).toEqual({ success: true });
    expect(recurringQuery.update).toHaveBeenCalledWith(
      expect.objectContaining({
        is_active: false,
      }),
    );
    expect(recurringQuery.eq).toHaveBeenCalledWith("id", "rec-2");
    expect(recurringQuery.eq).toHaveBeenCalledWith("user_id", "user-1");
  });
});
